# Generated by Django 3.2.7 on 2021-10-03 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
